import { NavBar } from "@/components/NavBar";
import "./globals.css";
import { Outfit } from "next/font/google";

const outfit = Outfit({ subsets: ["latin"], weight: ["300", "500"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app"
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={`${outfit.className} bg-[#10141E] font-light text-white`}>
                <NavBar />
                <main>{children}</main>
            </body>
        </html>
    );
}
